# Generated by Django 5.0.7 on 2025-02-22 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('JavaScript', 'JavaScript'), ('SQL', 'SQL'), ('Django', 'Django'), ('React', 'React'), ('SpringBoot', 'SpringBoot')], max_length=250)),
                ('communication', models.CharField(choices=[('*', '*'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=50)),
                ('technical', models.CharField(choices=[('*', '*'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=50)),
                ('programming', models.CharField(choices=[('*', '*'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=50)),
                ('conducted_on', models.DateTimeField(auto_now=True)),
                ('conducted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducted_by', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_rating',
            },
        ),
    ]
