# Generated by Django 5.0.7 on 2025-02-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='remarks',
            field=models.CharField(default='', max_length=250),
        ),
    ]
