# Generated by Django 5.1.6 on 2025-02-22 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_ratings_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='conducted_on',
        ),
    ]
