# Generated by Django 5.1.6 on 2025-02-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_remove_ratings_conducted_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='conducted_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
