# Generated by Django 5.1.6 on 2025-02-24 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_ratings_conducted_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='conducted_on',
        ),
    ]
