# Generated by Django 5.1.6 on 2025-02-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_remove_ratings_conducted_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='conducted_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
