# Generated by Django 5.1.6 on 2025-02-27 17:36

import django.core.validators
import django.db.models.deletion
import hr.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_ratings_conducted_on'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MockScheduling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.FileField(max_length=250, upload_to=hr.models.MockScheduling.mock_schedule_path, validators=[django.core.validators.FileExtensionValidator(['csv'])])),
                ('subject', models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('JavaScript', 'JavaScript'), ('SQL', 'SQL'), ('Django', 'Django'), ('React', 'React'), ('SpringBoot', 'SpringBoot')], max_length=250)),
                ('scheduling_date', models.DateField()),
                ('scheduling_time', models.TimeField()),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mock_scheduling',
            },
        ),
    ]
