# Generated by Django 5.1.6 on 2025-02-20 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pno', models.CharField(max_length=50)),
                ('add', models.TextField()),
                ('course', models.CharField(default='Python Fullstack Development', max_length=50)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='students_profiles/')),
                ('resume', models.FileField(upload_to='students_resumes/')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_profile',
            },
        ),
    ]
