# Generated by Django 5.0.7 on 2025-02-25 05:19

import django.core.validators
import student.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='course',
            field=models.CharField(choices=[('Python Fullstack Development', 'Python Fullstack Development'), ('Java Fullstack Development', 'Java Fullstack Development'), ('MERN Fullstack Development', 'MERN Fullstack Development'), ('Fullstack Testing', 'Fullstack Testing')], default='Python Fullstack Development', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='resume',
            field=models.FileField(upload_to=student.models.StudentProfile.rename_resume, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc'])]),
        ),
    ]
